// "use client";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
// import Sidebar from "../../components/Sidebar";
// import Header from "../../components/Header";
// import Head from "next/head";
import Layout from "../../components/Appayout";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="p-4 pl-0 flex w-full bg-white">
        {/* <Sidebar />
        <div className="mb-6 transition-all duration-500 ease-in-out lg:ml-[340px] ml-4 w-full">
          <Header />
          {children}
        </div> */}
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
